SELECT
    A.ID,
    A.EMAIL,
    A.FIRST_NAME,
    A.LAST_NAME
FROM DEVELOPERS A
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY A.ID